package com.wrapper.comunidadValenciana.Utils;

public class TextSanitizer {
    public static String accentMarkFixerCodification(String input){
        return input.replace("Ã¡", "á")
                .replace("Ã©", "é")
                .replace("Ã­", "í")
                .replace("Ã³", "ó")
                .replace("Ãº", "ú")
                .replace("Ã¼", "ü")
                .replace("Ã±", "ñ")
                .replace("Ã‘", "Ñ")
                .replace("Ã€", "À")
                .replace("Ãˆ", "È")
                .replace("ÃŒ", "Ì")
                .replace("Ã’", "Ò")
                .replace("Ã™", "Ù")
                .replace("Ã¨", "è")
                .replace("Ã¬", "ì")
                .replace("Ã²", "ò")
                .replace("Ã¹", "ù")
                .replace("Ã€", "À")
                .replace("Ã‚", "Â")
                .replace("ÃŠ", "Ê")
                .replace("ÃŽ", "Î")
                .replace("Ã”", "Ô")
                .replace("Ã›", "Û")
                .replace("Ã¤", "ä")
                .replace("Ã«", "ë")
                .replace("Ã¯", "ï")
                .replace("Ã¶", "ö")
                .replace("Ã¼", "ü")
                .replace("Ã„", "Ä")
                .replace("Ã‹", "Ë")
                .replace("Ã�", "Ï")
                .replace("Ã–", "Ö")
                .replace("Ãœ", "Ü")
                .replace("Ã‡", "Ç")
                .replace("Ã§", "ç")
                .replace("Ã‘", "Ñ")
                .replace("Ã±", "ñ")
                .replace("Ã ", "à")
                .replace("Ã\u0081", "Á")
                .replace("Ã\u0089", "É")
                .replace("Ã\u008D", "Í")
                .replace("Ã\u0093", "Ó")
                .replace("Ã\u009A", "Ú")
                .replace("Âª", "ª")
                .replace("Âº", "º")
                .replace("Ã¨", "è")
                .replace("Ã¬", "ì")
                .replace("Ã²", "ò");
    }
}
